### ISSUE TITLE
Github lecture bash commands

### ISSUE THREAD

**Issue by cyouh95** [Rucla-ed/rclass2#10]
Not sure if this is a Mac issue (see [here](https://unix.stackexchange.com/a/207139)) or just my computer, but things like `ls --help` and `ls --all` doesn't work for me. The shorthand `ls -a` works though, as well as `man ls` as the equivalent of `--help` for revealing the manual page. 

But since those commands are in the R chunks in `github_lecture.Rmd` (such as [here](https://github.com/Rucla-ed/rclass2/blob/963992b6d734c24b08b8815608e86c129cba4a00/lectures/github/github_lecture.Rmd#L550-L552)), I get an error if I try to knit the Rmd or run the R chunk. Might be good to remove those from R chunks to avoid confusion, or at least make a note somewhere that it might not work for everyone?

**Comment by ozanj** [comment]
good catch Crystal,

let's replace all the longhand options -- that don't work on mac w/ shorthand options.

as of now, I am not running a lot of the bash code chunks [eval = FALSE] but putting bash code in .Rmd code chunks seems like the most efficient way to insert bash code in the .Rmd lectures. [better than screenshots I think]. during lecture, I'm planning on running this code on git bash command line rather than running from .Rmd code chunks. But I agree this does feel a little clunky. I am open to other options!
