### ISSUE TITLE
Problem 7 question about using regex for a table

### ISSUE THREAD

**Issue by clemencedarriet** [Rucla-ed/rclass2#116]
I had a lot of trouble with this assignment i.e. it took me much longer than 
previous assignments, mainly with using regular expressions to define
portions of the table that we wanted to use. I couldn't get it to work and couldn't understand
why it wasn't working. It also made me wonder why we were
using regular expressions for a table. I understand if we are dealing with irregular data,
but I don't understand why we would need it with a table, which has clearly defined
rows and columns. When I selected the HTML code, it automatically grabbed the data and with a bit of reordering I was able to get it back to a table without regex, which is what Ben Skinner did (I was following his code), so why use regex in this instance?  @cyouh95 @ozanj @mpatricia01

**Comment by ozanj** [comment]
You are absolutely correct that regular expressions are not necessary to scrape this table. 

The problem set asked you to utilize regular expressions as a means of giving you more practice with regex. 

I agree that it would have been better for the problem set to ask questions where regular expressions are necessary or make things easier [rather than artificially using them]. apologies for the confusion. we just ran out of time!

**Comment by clemencedarriet** [comment]
Ah ok, I was wondering if regex allowed us to be more precise or something like that. Thanks Ozan!
