### ISSUE TITLE
quick question

### ISSUE THREAD

**Issue by ZhouLinli** [Rucla-ed/rclass2#44]
so **find "a directory" -print | sed -e 's;[^/]*/;|____;g;s;____|; |;g'** is to print the tree structure of the directory? Am I understand it right?

**Comment by ozanj** [comment]
You are correct Linili!

this is a regular expression that essentially recreates the output of the "tree" command.

the reason we use this regular expression rather than simply typing the tree command is that the tree command is not installed on [most versions] of Git Bash/Terminal and requires an extra installation step that I didn't want to inundate students with.

here is a relevant [blog post](https://superuser.com/questions/531592/how-do-i-add-the-tree-command-to-git-bash-on-windows)

**Comment by ZhouLinli** [comment]
thanks!
