### ISSUE TITLE
Learned: Revert vs Reset

### ISSUE THREAD

**Issue by lperales00** [Rucla-ed/rclass2#50]
I was stuck on this part of the assignment because I couldn't understand what revert was doing with my commits.  Please correct me if I am wrong, but I guess the easiest way I could explain it is that revert will go to any commit at any point in time in the history and undo it, leaving a "receipt or track change" behind as a reverted commit while removing the changes that were made in that specific commit. Reset will remove the commit starting with the most current commit and go backwards until you reach the desired commit?. It deletes any trace of the commit as if it was never created (no receipt or track changes). When working in groups it is advised to do reverts instead of reset.

**Comment by irmacastaneda0822** [comment]
Hi Lorraine, I believe you are right. 

- Git revert <commit_hash> returns to a specific earlier commit (identified with the commit hash) and creates a new commit that reverts the change (including the change specified with the commit hash). I'm guessing the new commit is what you call "leaving a receipt or track change."
-To my understanding git reset will completely remove all past commits, and will point the head to a specific commit hash. 

Since git reset removes past commits, it is not advised to do git reset when working in groups. 

Hope this helps! Also, if I'm wrong please correct me anyone!

**Comment by clemencedarriet** [comment]
This is also my understanding so hopefully we're on the right track!
