### ISSUE TITLE
Problems with git revert & use git commit regularly

### ISSUE THREAD

**Issue by aridimagiba** [Rucla-ed/rclass2#57]
![image](https://user-images.githubusercontent.com/62869110/79115344-7142cd80-7d3a-11ea-86d3-388432cf167a.png)

I have been going in circles about the 'git revert' command. I have committed my changes to 'problemset2.R' then try to revert again. But this time around I run into the unmerge paths issues. Are there resources anyone can recommend how to troubleshoot? 

Also I learned make a habit of committing your changes to git. I completed the problem set hours ago but in my quest to figure out the git revert issue I accidentally lost all my saved work in my rmd file.

**Comment by mpatricia01** [comment]
@aridimagiba I think you are having issues because you are trying to revert your last commit, but you have not committed new changes to your repository. The way revert works is say you make changes to your .Rmd file, you commit those changes, and then change your mind. Then you can look at your git log to see the hash of your last commit and revert the changes. Send me an email and we can meet later today or this week and troubleshoot!

**Comment by ozanj** [comment]
good question @aridimagiba 

I think I didn't do a great job going through all the commands to "undo" changes [partially, cuz I was/am still in the midst of learning them myself].

at some point in the next few weeks, I plan to revise that section of the github_lecture.Rmd and plan to devote 30 minutes of class going over these again. in the mantime, do the best you can and my bad for not doing a great job teaching it the first time around.

@aridimagiba - make sure you "assign" me, Patricia, and Crystal when you create an issue. otherwise we will miss it!
