### ISSUE TITLE
Posting Announcements and Team Discussion 

### ISSUE THREAD

**Issue by cyouh95** [Rucla-ed/rclass2#6]
I've taken a look at how we can use Github for announcements and team discussions, etc. and it seems like creating [teams](https://github.com/orgs/Rucla-ed/teams) is an option. 

Teams can be public to all members in the organization or private to specified members (+ org owners). For each team created, there is a "Discussions" tab to make posts/threads. [[doc](https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/about-teams#team-pages)]

Possible teams to create:
- **announcements** [public] - _make announcements/post resources, etc._
  - I think notifications are automatically sent to everyone in a public discussion, but could also mention team name using `@org_name/team_name` in post
- **homework** [public] - _students can post general questions for all to see_
  - Could possibly create nested teams under the main homework team (e.g., homework_1, homework_2) to keep posts separate if needed, though not sure if that's necessarily the "correct" purpose for creating nested teams
- **team_1**, **team_2**, etc. [private] - _private to the groups of 3 students (+ org owners)_

The other alternative would be to use Github issues - but I don't think there's a way to create private posts, and the posts would have to be associated w/ a particular repo (e.g., [rclass2](https://github.com/Rucla-ed/rclass2/issues)).

Only thing about the team discussion posts is I don't think there's a way to tag/organize posts using labels, like how we can w/ issues, but don't think that should be too big a problem if there's not going to be a huge amount of posts?

**Comment by ozanj** [comment]
nice summary and investigation Crystal!

I like the idea of creating teams for announcements [public, everyone in class is a member]

I also like the idea of creating private teams for homework groups. is it possible for the org owners (us) to not have access too? I don't want students thinking that "big brother" is always watching over them.

for questions about homework and course material, I'm thinking that students should just use github issues. because becoming comfortable with "issues" is a core part of learning how to use git/github. no need to have any nesting structure (e.g., nesting issues within homework_1, homework_2). what are the assignment possibilities on these issues? possible to have default assignment to the whole class? [everyone gets an email]. not sure if this is desirable, but just curious. I'm not 100% set on using regular github issues for homework/course material questions. would like to hear what you all think are pros/cons.

**Comment by mpatricia01** [comment]
Thank you @cyouh95 !

I agree with @ozanj.  I like the idea of creating a public team for announcements and private teams for homework groups. I think it would be a good idea for groups to have their own discussion tab to talk about issues they are encountering in the problem sets and work through them together (at least that's the goal). Also agree with having students post questions using issues so that they can practice.

**Comment by cyouh95** [comment]
For private teams, I tried creating one and it didn't seem to automatically add all owners (ie. you guys) as members to the team - not sure if you guys are still able to access this [private_team](https://github.com/orgs/Rucla-ed/teams/private_team/discussions)?

As for pros and cons of using issues for homework/course questions...
- Pros
  - Could use labels to organize `homework_1`, `homework_2`, etc.
  - Practice using issues
    - (I think we once we create the public `announcements` team, we can notify everyone using `@Rucla-ed/announcements`)
- Cons
  - Students would need to access 2 different locations for [announcements & team discussions](https://github.com/orgs/Rucla-ed/teams) and the [homework/course questions](https://github.com/Rucla-ed/rclass2/issues)
  - Not too sure about this (and might just be me!)... but it feels like issues created on the [rclass2 repo](https://github.com/Rucla-ed/rclass2/issues) should technically be related to issues about the class itself (e.g., what to change about certain files in this rclass2 repo, topics we currently have [here](https://github.com/Rucla-ed/rclass2/issues), etc), whereas discussion about problem sets sounds like they belong more in the discussion forum
    - But it might make sense to provide feedback about their submitted assignments on the issues page of their [individual repos](https://github.com/Rucla-ed). Maybe students could get some practice w/ issues there? But of course, those issues wouldn't be public to all other students... not too sure what's the best option!
