### ISSUE TITLE
git rev-

### ISSUE THREAD

**Issue by ZhouLinli** [Rucla-ed/rclass2#60]
for "git rev-list HEAD | tail -n 1", can you explain the part "| tail -n 1"?

**Comment by cyouh95** [comment]
The `tail` command displays the last few lines of some given input. With the `-n` option, we can specify exactly how many lines to display. 

`git rev-list HEAD` outputs a list of commit hashes. We can then use the `|` (pipe command) to use that output as the input for the `tail` command that follows. So together, this is fetching the last line in the list of commit hashes (which is the hash of the initial commit, since the list is in reverse chronological order) Hope this helps!

**Comment by ZhouLinli** [comment]
thanks!!!!
