### ISSUE TITLE
why not initiate with "README"

### ISSUE THREAD

**Issue by ZhouLinli** [Rucla-ed/rclass2#61]
when we create local first and then clone URL from remote in Github, why we must NOT check "initiate README" but do that in the local repo?

Can't we initiate README in GitHub (remotely)?

**Comment by cyouh95** [comment]
When we check the "initiate README", it'll create an initial commit on the remote repo that contains the README file. But in the case where we have an existing local repo, we usually have commits already in there that we want to push to the remote. So, we'll probably want the remote to start off empty without any pre-existing commits (ie. the README commit) in there, such that our local is up-to-date w/ the remote before we push. (It'll just be easier so that we don't need to worry about pulling any remote commits we don't have). In this case, we'd also be using `git remote add` to add the remote rather than using `git clone`.

In this case of cloning a new remote repository, I think in the lecture we suggest to check the "initiate README". But just tested it out now - I think it might also be fine if you don't check that option! You should still be able to clone the remote all the same, then add/commit anything you want before pushing.

Hope this covers what you were asking/let me know if there's anything I could clarify!

**Comment by ZhouLinli** [comment]
this clarifies a ton!!!thanks crystal!!
