### ISSUE TITLE
Problemset 3 - Part 4, Question 11

### ISSUE THREAD

**Issue by augias** [Rucla-ed/rclass2#62]
My logs don't match up to what the question suggests, and I'm afraid the issue might not have a clear solution. The problemset asks:

> Use the `git cat-file` command to print out the contents of the commit object for the commit whose message is `modify bar chart on master`. Find the hash of the parent commit and look for it in the commit log. ...

and later

> Note that the parent commit in this case is not just the previous commit in the commit log. Why is that?

In my case, the git log shows the parent commit is definitely the previous commit, unlike what the question suggests. I assume I made lots of *decisions* at different stages and out of order from the instructions or else misunderstood the logic of looking at which parent hashes to look at. 

My main point is I can't answer the question except to say that didn't happen to me.

Output below. The relevant commit hashes are in asterisks

    fernando@pepino:~/Documents/263 R/rclass2/mora_ps3$ git cat-file -p 7da1f71
    tree c4e49c8876c36ce5e396a127e2e37c3ed858df1d
    parent 64dd3bc5bc96037e9c48d5fb73e0a288fd962705 <-------------
    author augias <augias.amena@gmail.com> 1587018743 -0700
    committer augias <augias.amena@gmail.com> 1587018743 -0700

    modify bar chart on master
    
    fernando@pepino:~/Documents/263 R/rclass2/mora_ps3$ git cat-file -p 64dd3bc5bc96037e9c48d5fb73e0a288fd962705
    tree 45d53e58da4576133f50f877013b1d3bf35e9d47
    parent 9eef944713d91afb3ba8a7e7734499852b106c77 <-------------
    author augias <augias.amena@gmail.com> 1587018546 -0700
    committer augias <augias.amena@gmail.com> 1587018546 -0700

    modify bar chart on dev

    fernando@pepino:~/Documents/263 R/rclass2/mora_ps3$ git log
    commit 23dfe6021ffa8dc91d5c2c627d344c49af14f6c0 (HEAD -> master, remote_ps3/master, remote_ps3/HEAD)
    Author: augias <augias.amena@gmail.com>
    Date:   Thu Apr 16 00:12:22 2020 -0700

    Add problemset3.Rmd to master branch of mora_ps3
    
    commit 7da1f71055733cc1a76d5fa52035b4afe1eab639
    Author: augias <augias.amena@gmail.com>
    Date:   Wed Apr 15 23:32:23 2020 -0700
    
    modify bar chart on master
    
    commit 64dd3bc5bc96037e9c48d5fb73e0a288fd962705 <-------------
    Author: augias <augias.amena@gmail.com>
    Date:   Wed Apr 15 23:29:06 2020 -0700
    
    modify bar chart on dev
    
    commit 9eef944713d91afb3ba8a7e7734499852b106c77 <-------------
    Author: augias <augias.amena@gmail.com>
    Date:   Wed Apr 15 23:27:16 2020 -0700
    
    modify scatterplot on dev

**Comment by cyouh95** [comment]
@augias It seems you might have been on the `master` branch instead of `dev` when you made the commit `modify bar chart on dev` (**64dd3bc**), which is why it's appearing as the parent of `modify bar chart on master` (**7da1f71**) (see [here](https://github.com/Rucla-ed/mora_ps3/network))

Sorry if there were any confusion in the problem set instructions! The steps should have mentioned when to switch branches (see Part IV Q1 and Q4) - but let us know if anything was unclear.

As for the question, perhaps you could still answer it by thinking about it conceptually? As a hint - If the `modify bar chart on dev` was made on the `dev` branch, then the parent commit of `modify bar chart on master` should be `bar chart 3`.

@mpatricia01 @ozanj - What do you think?

**Comment by mpatricia01** [comment]
@cyouh95 , yes I agree! It appears that you may have made those changes while you were on the master branch instead of the dev branch. 

As Crystal mentioned, even if your output is different, you could answer the question by thinking about it conceptually. Let us know if you have additional questions. My office hours are today from 12-2 and/or by appointment!

**Comment by augias** [comment]
Thats what i figured, missing an instruction since I am going back and forth from the problem set, the r file, and my console. I'll think on the logic behind the question and see what I come up with.

Thanks @cyouh95, Thanks @mpatricia01
