### ISSUE TITLE
Question about commiting "merge dev and master"

### ISSUE THREAD

**Issue by irmacastaneda0822** [Rucla-ed/rclass2#64]
Hi, I had an issue with Part IV, Question 10.

After I manually resolved the merge conflict and added my r script filed, I tried to commit my changes with git commit -m"merge dev and master." But R returned this error: fatal: cannot do a partial commit during a merge.

I ended up doing some googling and did: git commit -am"merge dev and master"
This ended up working , but I'm still confused on what the error was. Do you know what this error means and what the -am adds to the commit?

Thanks so much!
@ozanj  @cyouh95  @mpatricia01 

<img width="869" alt="Screen Shot 2020-04-16 at 9 12 37 PM" src="https://user-images.githubusercontent.com/59708601/79531394-11dd0a00-8027-11ea-93ab-7f4fcec5aefc.png">

**Comment by mpatricia01** [comment]
Hi @irmacastaneda0822 ,

Not sure why you received that error. I did notice that you wrote `git commit m-` instead of `git commit -m`. Not sure if that prompted your error? I believe `-a` tells git to automatically stage modified/deleted files. My guess is that `-am` will automatically stage modified/deleted files and add a message to commit. 

@cyouh95 @ozanj any thoughts?

**Comment by cyouh95** [comment]
I agree! It looks like that error was just due to the typo (`m-` instead of `-m`). 

From the docs, it seems `git commit -am "your message"` is just the equivalent of `git add .` + `git commit -m "your message"`. But in your case @irmacastaneda0822, I think just trying `git commit -m "your message"` again would have also worked since your files were already staged.

**Comment by irmacastaneda0822** [comment]
Thank you so much Patricia and Crystal! Sorry it was a silly typo. Haha I had gotten this error before, so I thought I'd post it. I just have to be careful about these typos!
