### ISSUE TITLE
Question about the parent commit

### ISSUE THREAD

**Issue by tinghj17** [Rucla-ed/rclass2#65]
Hi, I have a question about Part IV, Question 11 "why the parent commit is not just the previous commit in the commit log". I think the reason that "barchart 3" is the parent commit is because that is the last commit made on master branch. When we merged dev into master and added the r script file, we made changes based on the last commit on master branch.

I am not sure if I understand the definition of the parent commit correctly. Thanks for your help!!

@ozanj @cyouh95 @mpatricia01

**Comment by ozanj** [comment]
Generally speaking, the "parent commit" for a commit is the immediately previous commit.

for example: COMMIT 1 >>> COMMIT 2 >>> COMMIT 3 >>> COMMIT 4

the "parent commit" for "COMMIT 3" is "COMMIT 2" 

A 3-way merge creates a new commit. unlike, most commits, the commit associated w/ a 3-way merge has two parent commits, one for the master branch and one for the other branch because it incorporates data from the commit sequences of two different branches.

the visualizations in the required reading here could be helpful: https://www.atlassian.com/git/tutorials/using-branches/git-merge

also, a relevant quote from that reading: "[3-way] Merge commits are unique against other commits in the fact that they have two parent commits. When creating a merge commit Git will attempt to auto magically merge the separate histories for you. If Git encounters a piece of data that is changed in both histories it will be unable to automatically combine them. This scenario is a version control conflict and Git will need user intervention to continue."

let me know if this  helps!
