### ISSUE TITLE
Class website

### ISSUE THREAD

**Issue by mpatricia01** [Rucla-ed/rclass2#7]
@ozanj can you take a look at the class website https://rucla-ed.github.io/rclass2/ and let me know what you would like me to add/change. Right now the collapsibles are empty, but will be linking html file and .Rmd file for each week. Also, once we confirm weekly topics I can rename collapsibles by topic (e.g. Week 1 to Week 1: Github etc.). Specifically let me know if you want me to change the language of the class description (just copied from promo email). 

@cyouh95 feedback is welcomed as well!

**Comment by cyouh95** [comment]
I think this looks really nice! Very clean, and I like the icons you added for email/twitter/github links!

Only feedback I have is maybe make the sidebar a bit more narrow and main screen wider?

**Comment by ozanj** [comment]
@mpatricia01 @cyouh95 

Website looks great!

need some changes in structure.

main thing is that the lectures will not be named for each week. rather, lectures named for a topic. some lectures (e.g., github) we will take several weeks to work through. other lectures (e.g, ggplot) will be only part of one week. so maybe the outline structure of the website would be something like [don't use these exact titles]

- syllabus/resources
- lectures/topics [sub-heading for topics (e.g., github, ggplot, date/time, json/api, iteration, functions, regular expressions, et.
- weekly reading and assignments [would list the reading and assignments that must be done before class that week]

The reason I don't want to have a structure of lecture = week is because some topics don't fit easily in a week [too big or too small]. and since this quarter is first draft of the class, I just want us to focus on doing best job possible explaining topics. and we will slow down or speed up the weeks as necessary.

thoughts?

**Comment by mpatricia01** [comment]
Thank you both @cyouh95 @ozanj for the feedback. 

I agree with naming lecture topics instead of weeks. I don't think I am understanding correctly. Do you want me to only have three collapsibles (syllabus/resources, topics, readings/assignments)? Or instead of naming collapsibles by week (e.g. Week 1, Week 2, etc.) I rename them by topic (e.g. github, ggplot, etc.) and within each collapsible I add weekly readings/assignments?

**Comment by ozanj** [comment]
@mpatricia01 @cyouh95 

I forgot that term "collapsibles". let's say that the level-1 headings are the collapsibles. 

so the three collapsibles are as follows:

- Syllabus & class resources
- Lectures by topics
- Reading and assignments by week

how does this sound?

**Comment by ozanj** [comment]
we should probably also record and post video lectures.

maybe these would be posted within "lectures by topic" and then there would be a brief description like "github lecture, week 2, covering section x.x on branches through x.x on merges" or something. 

lemme know if you have other ideas.

**Comment by mpatricia01** [comment]
@ozanj I see what you are saying and I don't necessarily disagree, but do you think keeping lectures by topics and readings/assignments by week might be confusing? I can change it up and see how it looks. Also, it would be helpful to have the syllabus ready so I can know what readings to add to that tab.

**Comment by ozanj** [comment]
I do agree it could be confusing, but I think better than alternatives

could collapsibles be this:

- Syllabus & class resources
- Lectures (by topic)
- Weekly assignments and readings

additionally/alternatively we could have two levels of collapsibles. for example:

weekly assignments and readings >> week 2 [then separate bullets for assigned reading and for links to problem set]

**Comment by cyouh95** [comment]
Maybe another way is to have there be links in the left-hand sidebar for the 3 "level-1" headings (`Syllabus & Class Resources`, `Lectures by Topic`, `Weekly Assignments & Readings`) - similar to how the `Home`, `About`, and `Class Resources` links are working [here](https://ozanj.github.io/rclass/).

Then if you click `Lectures by Topic`, the main screen would show the collapsibles for each topic. If you click `Weekly Assignments & Readings`, the collapsibles would be for Week 1, Week 2, etc...?

**Comment by mpatricia01** [comment]
Can you take a look at it now? Let me know how you want me to word assignments and readings please @ozanj. @cyouh95
