### ISSUE TITLE
disappearing code

### ISSUE THREAD

**Issue by clemencedarriet** [Rucla-ed/rclass2#74]
This weird thing was happening to my R file yesterday where I would open up my previously saved and close R file and the code I had previously written was gone. I was able to copy it from the history tab but didn't understand why this was happening. Has this happened to anyone? @ozanj @mpatricia01  @cyouh95

**Comment by cyouh95** [comment]
@clemencedarriet Do you remember which step you were on when this happened? Could it be because you had switched branches?

If you had made changes to your R file on one branch and committed it there, then switched back to an older branch, those changes you've made wouldn't appear on the latter, unless you merge the first branch in.

**Comment by clemencedarriet** [comment]
Ok that makes sense I do remember having changed from master/dev a few times around the time that the code was disappearing. Thank you!
