### ISSUE TITLE
str_sub() , what if we want to start at different position for different elements

### ISSUE THREAD

**Issue by ZhouLinli** [Rucla-ed/rclass2#89]
in the problem set 5, one task is to create a "short_web" object that removes the "http://www." part of the URL. However, what if the links do not follow the same format "http://www."? how can we str_sub()? 
see picture below -- different elements has a different format. it seems str_sub(start=12, end=-1) cannot be used universally because start does not equal to 12 for every element.

<img width="334" alt="Screen Shot 2020-04-28 at 1 48 25 PM" src="https://user-images.githubusercontent.com/53378364/80536303-0529b180-8957-11ea-8ee2-f1563f84ffea.png">

**Comment by ozanj** [comment]
great question!

lots of ways to do this. one approach that comes to mind: you can create separate objects or variables that denote the position you want to start with (for example by identifying the position number of the colon ":" or the two forward slashes). and then use the position number variables as input arguments to the str_sub() function.

we will be learning skills like this in the subsequent two weeks

**Comment by ZhouLinli** [comment]
Thanks @ozanj , can you specify how to make an object "position" that denotes "//"? 
object<- ??

**Comment by ozanj** [comment]
we will be covering this in the next two weeks, which focus on regular expressions. if you want to read ahead, the answer to your specific question can be found in section 14.4.6 of "r for data science" by wickham, which states:

"str_locate() and str_locate_all() give you the starting and ending positions of each match. These are particularly useful when none of the other functions does exactly what you want. You can use str_locate() to find the matching pattern, str_sub() to extract and/or modify them."

I only know this because I am reading this right now! I think good to wait on this though because regular expressions are tough and we will try to give folks a gentle introduction.

**Comment by ZhouLinli** [comment]
great thanks! @ozanj

**Comment by ozanj** [comment]
great questions! happy to help Linli!
