### ISSUE TITLE
Question about pull request

### ISSUE THREAD

**Issue by Kei-qss** [Rucla-ed/rclass2#96]
For the last part of the p-set 5, I wanted to make a pull request to merge my dev branch to the master in GitHub and pushed the button "New Pull Request," but I got the following message and could not move forward. Could you assist me with this? Thank you in advance.

![Screen Shot 2020-05-02 at 00 25 28](https://user-images.githubusercontent.com/52636747/80858290-637fba00-8c0d-11ea-84d7-249c98d0abb4.png)

@ozanj @cyouh95 @mpatricia01

**Comment by ozanj** [comment]
the problem may be that the two branches don't share any of the same history. 

maybe this post helpful [link](https://stackoverflow.com/questions/53844405/github-pull-request-there-isnt-anything-to-compare)

perhaps there were no commits to master branch prior to creating the branch dev_kt and, if so, then the branches cannot be merged because there is no common commit to start from.

**Comment by Kei-qss** [comment]
Thank you, I understood the issue. Do you know any way to fix this? I tried pulling the master of remote to the master of locale, merging it to my dev branch, and pushing it to the remote, but this didn't make any difference..

**Comment by ozanj** [comment]
I can create a new branch off the master. Add ur script to the branch, and
then merge to master

**Comment by ozanj** [comment]
Meant to say u can create new branch off master
